// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Protos/test.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace GrpcGreeter {
  public static partial class Test
  {
    static readonly string __ServiceName = "Test.Test";

    static readonly grpc::Marshaller<global::GrpcGreeter.HiRequest> __Marshaller_Test_HiRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::GrpcGreeter.HiRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::GrpcGreeter.HiReply> __Marshaller_Test_HiReply = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::GrpcGreeter.HiReply.Parser.ParseFrom);

    static readonly grpc::Method<global::GrpcGreeter.HiRequest, global::GrpcGreeter.HiReply> __Method_Hi = new grpc::Method<global::GrpcGreeter.HiRequest, global::GrpcGreeter.HiReply>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Hi",
        __Marshaller_Test_HiRequest,
        __Marshaller_Test_HiReply);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::GrpcGreeter.TestReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of Test</summary>
    [grpc::BindServiceMethod(typeof(Test), "BindService")]
    public abstract partial class TestBase
    {
      public virtual global::System.Threading.Tasks.Task<global::GrpcGreeter.HiReply> Hi(global::GrpcGreeter.HiRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(TestBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_Hi, serviceImpl.Hi).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, TestBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_Hi, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::GrpcGreeter.HiRequest, global::GrpcGreeter.HiReply>(serviceImpl.Hi));
    }

  }
}
#endregion
